### ISSUE TITLE
[QA] 텃밭일기 등록하기 본인 직접 입력하는 상황 추가하기

### ISSUE THREAD

**Issue by byeolhaha** [everyone-s-garden/front-v2#120]
## 내용 설명
![image](https://github.com/user-attachments/assets/0f5d26e2-8de8-45b9-bdbf-0264558bb132)

텃밭 일기 등록하기에서 "지도에 등록된 텃밭이 아닌 경우"를 위한 예외 케이스 적용하기
## 작업 내용

- [ ] 텃밭명을 본인이 직접 입력하는 경우에 위치를 검색해서 등록할 수 있도록 기능 추가하기

## 세부 작업 기간

10월 20일까지

**Comment by hyoribogo** [comment]
@byeolhaha 이거 정확히 어떤 플로우인지 알려주실 수 있을까요? api도 없는 것 같아요!

**Comment by byeolhaha** [comment]
@hyoribogo 
현재, **텃밭 일기 작성하려면 지도에 등록된 텃밭만 가능**합니다. 
하지만 **대부분의 유저들은 지도에 등록된 텃밭이 아닌 텃밭 관해서 일기를 작성하고 싶어할 거 같아요**. 
그래서 **`텃밭 정보` 검색시 나오지 않는 텃밭인 경우에 본인이 직접 입력할 수 있도록** 하려고 합니다.

주소 검색은 건우님이 사용하지 주소 검색 API 사용하시면 될 거 같습니다.
API는 지금 붙어있는 텃밭 일기 등록하는 API 사용해주시면 됩니다.

**Comment by hyoribogo** [comment]
@byeolhaha 현재 나의 텃밭 등록하는 api는 따로 주소값을 받지 않고 검색해서 나온 텃밭의 id를 페이로드로 받고 있습니다.
사용자가 원하는 대로 이름과 위치를 정해서 등록하려면 api 수정이 필요할 것 같습니다.

**Comment by byeolhaha** [comment]
@hyoribogo  오 그렇네요! 제가 하나 만들고 말씀드리겠습니다!

**Comment by byeolhaha** [comment]
@hyoribogo 기획변경으로 인한 API 수정이 완료되었습니다. 
관련 피그마와 [레스트독스](https://every-garden.kro.kr/docs/index.html#_%EB%82%B4%EA%B0%80_%EA%B0%80%EA%BE%B8%EB%8A%94_%ED%85%83%EB%B0%AD_%EB%93%B1%EB%A1%9D) 확인 부탁드립니다.
